# Generated by Django 5.2.4 on 2025-11-19 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0009_remove_userprofile_name_userprofile_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='full_name',
            new_name='name',
        ),
    ]
