# Generated by Django 5.2.4 on 2025-11-19 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extractor', '0010_rename_full_name_userprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
    ]
